matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: "12.1.0"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    # Windows currently doesn't support encrypted variables.
    # Once supported uncomment this out & remove build with Docker
    #
    #- os: windows
    #  language: node_js
    #  node_js: "8"

    #- os: linux
      #services: docker
      #language: generic

cache:
  npm: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  - npm install
  - npm run dist

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: $HOME/dist/*.dmg
  skip_cleanup: true
  draft: false
  on:
    tags: true