matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: "12.1.0"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  npm: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  - npm install
  - npm run dist
  - ls
  - ls ./dist

branches:
  except:
    - Dev
  only:
    - master

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "afrenchrussian"
  - git config --local user.email "afrenchrussian@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  skip_cleanup: true
  file:
    - "./dist/"