version: 0.1.5.1

environment:
  matrix:
    - nodejs_version: "12.1.0"

branches:
  only:
    - master
  except:
    - Dev

cache:
  - node_modules -> package.json
  - '%APPDATA%\npm-cache'

install:
  - ps: Install-Product node $env:nodejs_version
  - export TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - npm install

build_script:
  - npm install
  - npm run dist
  - ls dist

#deploy:
 # - provider: GitHub
  #  release: $(TAG)
