environment:
  matrix:
    - nodejs_version: "12.1.0"

branches:
  only:
    - master
  except:
    - Dev

cache:
  - node_modules -> package.json
  - '%APPDATA%\npm-cache'

artifacts:
  - path: dist/GSM Setup *.*.*.exe
    name: "setup"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build_script:
  - npm install
  - npm run dist
  - ls dist

deploy:
  - provider: GitHub
    release: 0.1.9
    draft: false
    prerelease: false
    auth_token: $(GITHUB_TOKEN)